### PR TITLE
Number of records

### PR DESCRIPTION
**Pull request by jrchudy**
This PR addresses issues #753 and #785. Both of these buttons also have a tooltip added to them. The tests that I included test the implementation of:
 - clicking the button to open the input and clicking again to close it
 - making sure the error case occurs properly and alert shows up when a number greater than the max is input
 - it also verifies that multiple forms are indeed added when the user submits an appropriate value 

The tests do not test filling out the forms and submitting them to the database. I spent some time trying to use the `testPresentationAndBasicValidation` function in `../specs/recordedit/helpers.js` to fill in my forms and submit them but that function is too specific to the case of adding 1 row at a time and verifying that new one can be filled out. I would have to heavily modify that function or write a whole new function for filling out my forms, to test this functionality that is already tested in a slightly different context.

This functionality can be tested [here](https://dev.isrd.isi.edu/~jchudy/chaise/recordedit/#1/legacy:dataset). 

Assigning to @howdyjessie and mentioning @shinyichen.

### CODE REVIEW

**Comment by howdyjessie** [comment]
- The input field is taller than the checkmark button, anyway to fix that and make them aligned?
- Should the pencil icon be that? We use it to mean editing things, which I kinda get why you'd use it in this context (the user is editing how many rows to add), but I don't find it immediately clear what I'm editing. How about a &#65049; (`&#65049;`) or &#8943; (`&#8943;`) like a context menu?  Or even `glyphicon-triangle-bottom` to indicate there's a dropdown there?

**Comment by howdyjessie** [comment]
Oops I just realized you said this morning you're retracting this PR! Sorry for the premature comments.

**Comment by jrchudy** [comment]
@howdyjessie, this issue is ready for review. I have since fixed the position of the input control so it doesn't get placed on top of a trash can icon and made the input group look better.

**Comment by howdyjessie** [comment]
This looks good, I've merged it.

**Pull request merged**
