### PR TITLE
 Fixed white space issues while printing record page

### PR DESCRIPTION
**Pull request by Divyata-Singh**
- Made the record-side-pan as hidden while printing
- Adjusted the width of the table columns for printing
- Adjusted the page margins

### CODE REVIEW

**Comment by RFSH** [comment]
Can you deploy this on your user directory in rbk? (it's the same as gudmap) so we can compare what's on master and what you've changed by going to the same table that the issue description is suggesting.

Since this is UX issue, it's easier to review them by comparing the two. Also we should include @hongsudt so she can take a look at it and approve it.

**Comment by Divyata-Singh** [comment]
https://dev.rebuildingakidney.org/~divyatas/chaise/record/#2/Protocol:Protocol/RID=N-H98E
This is a sample link.

**Comment by jrchudy** [comment]
Changes look good. Before we merge this, please ask @hongsudt  to test this out and make sure everything is working as expected now (or at least better than before).

**Comment by hongsudt** [comment]
She have already looked at the style with her. Let's merge.

**Pull request merged**
