### PR TITLE
Action Colum

### PR DESCRIPTION
**Pull request by shinyichen**
PR for #838. Create an action column. 
* In recordset, column should have view|edit|delete actions. 
* In record, table have view|edit|delete or unlink.
* Update the table after delete or edit made.
* In recordedit modal, column should only have select action.
* Remove row click action from table.

### CODE REVIEW

**Comment by shinyichen** [comment]
You can test them here.
https://dev.isrd.isi.edu/~jchen/chaise/recordset/#1/legacy:dataset

**Comment by RFSH** [comment]
These are the bugs that I found while testing the behaviour on chaise.

- In case of edit on pure binary association tables, should use the same reference that is being used for unlink.
- When you edit a related reference, record page gets updated automatically but it is not the case for pure binary association tables (only updates on create and not edit).

-----
you can test it here: [https://dev.isrd.isi.edu/~ashafaei/chaise/record/#1/legacy:dataset/id=9](https://dev.isrd.isi.edu/~ashafaei/chaise/record/#1/legacy:dataset/id=9)

**Comment by shinyichen** [comment]
The generated edit link (when using entryEdit context), gives you entry in the associated table.  https://dev.isrd.isi.edu/~jchen/chaise/record/#1/legacy:data_type/term=Facial%20Images%2FLandmarks
(Is that what you meant?)

**Comment by shinyichen** [comment]
I pushed the changes that addressed the two issues. @RFSH

**Pull request merged**
