### PR TITLE
Help angular module

### PR DESCRIPTION
**Pull request by RFSH**
In the latest task that @rastogi-bhavya was working on, we decided to add a help page to explain how users can draw using the new drawing tools. After discussing this, we decided to go with a more "future proof" solution that can be used for generating future help pages that we want to host directly in chaise page (without directing them outside of chaise.)

So I added a new "help" app which is just a template for rendering markdown values. For adding new help pages, we just need to provide a `.md` file and some extra attributes. With this approach, we don't need to worry about the HTML and AngularJS side of things and just focus on the content of our documents. This solution is very similar in nature to what is done for deriva docs. 

I created this PR so @jrchudy and @hongsudt can see the approach and we can further discuss this solution. You can see how it works here:
https://dev.rebuildingakidney.org/~ashafaei/chaise/help/?page=viewer-annotation

We can later refactor our existing help pages ([markdown tags](https://dev.rebuildingakidney.org/chaise/recordedit/mdHelp.html) and [the switch-user one](https://dev.rebuildingakidney.org/chaise/lib/switchUserAccounts.html)), to use this new app.

---------
P.S.
@rastogi-bhavya I noticed that you were using HTML tags directly in your markdown, although that's acceptable in Github markdown parser, it's not acceptable by our internal parser. You should also stick with a relative path for images instead of an absolute path. That way your help pages work both in the app as well as Github. I modified one of your images, you can see how I did it and change the rest. With this new syntax, we're attaching specific classes to images that later we can modify. That being said, I think for now we should make sure this way of doing things is acceptable by all, then we can focus on the content of the help page.

### CODE REVIEW

**Comment by carlkesselman** [comment]
nice.

Where does the content actually live?  I recall that in the past we created a markdown armrest type that would be properly rendered…..

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Oct 28, 2020, 3:53 PM -0700, Aref Shafaei <notifications@github.com>, wrote:

In the latest task that @rastogi-bhavya<https://github.com/rastogi-bhavya> was working on, we decided to add a wiki page to explain how users can draw using the new drawing tools. After discussing this, we decided to go with a more "future proof" solution that can be used for generating future wiki pages that we want to host directly in chaise page (without directing them outside of chaise.)

So I added a new "wiki" app which is just a template for rendering markdown values. For adding new wiki pages, we just need to provide a .md file and some extra attributes. With this approach, we don't need to worry about the HTML and AngularJS side of things and just focus on the content of our documents. This solution is very similar in nature to what is done for deriva docs.

I created this PR so @jrchudy<https://github.com/jrchudy> and @hongsudt<https://github.com/hongsudt> can see the approach and we can further discuss this solution. You can see how it works here:
https://dev.rebuildingakidney.org/~ashafaei/chaise/wiki/?page=viewer-annotation

We can later refactor our existing wiki pages (markdown tags<https://dev.rebuildingakidney.org/chaise/recordedit/mdHelp.html> and the switch-user one<https://dev.rebuildingakidney.org/chaise/lib/switchUserAccounts.html>), to use this new app.

________________________________

P.S.
@rastogi-bhavya<https://github.com/rastogi-bhavya> I noticed that you were using HTML tags directly in your markdown, although that's acceptable in Github markdown parser, it's not acceptable by our internal parser. You should also stick with a relative path for images instead of an absolute path. That way your wiki pages work both in the app as well as Github. I modified one of your images, you can see how I did it and change the rest. With this new syntax, we're attaching specific classes to images that later we can modify. That being said, I think for now we should make sure this way of doing things is acceptable by all, then we can focus on the content of the wiki page.

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/informatics-isi-edu/chaise/pull/2024

Commit Summary

  *   Created view-annotation.md [ci skip]
  *   Adding screenshots for annotation documentation [ci skip]
  *   Adding login Image
  *   Update view-annotation.md
  *   Images Update
  *   Adding images to view-annotation.md [ci skip]
  *   Inline image test [ci skip]
  *   Add all the images inline [ci skip]
  *   introduce wiki app

File Changes

  *   M Makefile<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52> (19)
  *   M common/navbar.js<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-2d0212e4bca4558e79dda92d93a12c12f46d6575ebf79f93fa9939ba32c99ab3> (2)
  *   A common/styles/scss/_wiki-app.scss<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-1658925de7b5cbb71f5323a63199cf0a5e0a794e59baeac6efcea05570aa25b0> (40)
  *   M common/styles/scss/app.scss<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-4cf27b1109f19aeec311881a06670c3bccafd4e964d9d75a10408847408e69d7> (1)
  *   M common/utils.js<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-98a178f109142f3af2fd633816369aec7a828f1d2148d30cbc23fb7aa8fed8ff> (14)
  *   A wiki/home.md<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-5d5c232f75f3bee083ea5ff5d4aafbd0b3085cfa3b5c5a7069a98e4331e7d1f5> (3)
  *   A wiki/index.html.in<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-ba13a26017834bd95a3d217c0e1c3cadaace99c4d14ffb8a4c56cf7d26eb302a> (34)
  *   A wiki/resources/annotation-documentation-images/AnnotationToolbar.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-6408b5af1cdf96205e5e78533ef5aa6967d18c87cb6136ee0bb253d34fde1e0c> (0)
  *   A wiki/resources/annotation-documentation-images/Circle.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-2955aeca55728d907349d16ef7e1db89b5ec49b6d72b665e6269d03a7fcbb739> (0)
  *   A wiki/resources/annotation-documentation-images/ColorPicker.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-aed6b8f4fb6a08315565651e93709b7a7e2bee9f0ffd4edf01e5cec998bb4125> (0)
  *   A wiki/resources/annotation-documentation-images/CreateAnnotationPanel.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-1ead177d882d33c117973f37591bd959ac23294bcbeac149c706a3b443835c3b> (0)
  *   A wiki/resources/annotation-documentation-images/DeleteButton.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-6e920b302adb0eeff80efeed1048c256482ca76d735db12a701cffdffe96b05d> (0)
  *   A wiki/resources/annotation-documentation-images/EditAnnotationPanel.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-a80d0aed658e1891d96210a40756f4fdfb09acab58f81940c92df6670ec65225> (0)
  *   A wiki/resources/annotation-documentation-images/Login Check.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-316b80c7a43d5fa280e2d556dd1af23becf1df279f0702a83d5e065db5a10bef> (0)
  *   A wiki/resources/annotation-documentation-images/NewButton.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-1a27042c6c1f00ca3c6da14e793a62fd986171985c8f14ee1b8ba4500f161be9> (0)
  *   A wiki/resources/annotation-documentation-images/Path.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-04c55cdbcbcb36c8d1c3ec6a8917082e436dc65603669cb27e2fbda1bcf04734> (0)
  *   A wiki/resources/annotation-documentation-images/Rectangle.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-c225d29be196be7498073d846a1050c06d7eafbe00dbb73d6546bda593cd092d> (0)
  *   A wiki/resources/annotation-documentation-images/SaveButton.png<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-04adfba3f2eef11a6188257e2bf099ac8582bd774bae37a33d91bab7d249eb38> (0)
  *   A wiki/viewer-annotation.md<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-f8b7c964931b60378b6eb122fd045c6dd72e214895b2b5aa152321c70622a1ae> (60)
  *   A wiki/wiki.app.js<https://github.com/informatics-isi-edu/chaise/pull/2024/files#diff-c6ebe1ae1fc60180160d4fca2d26006735c80f922edb78968540ac3a1d63c17f> (90)

Patch Links:

  *   https://github.com/informatics-isi-edu/chaise/pull/2024.patch
  *   https://github.com/informatics-isi-edu/chaise/pull/2024.diff

**Comment by RFSH** [comment]
@carlkesselman The content is part of the chaise repository, under the same wiki folder. For example, this is the one page that we have right now:
https://github.com/informatics-isi-edu/chaise/blob/annotation-documentation/wiki/viewer-annotation.md

**Comment by RFSH** [comment]
I should also mention that I just wanted to show how this would work. We can change the style of the page and make it cleaner and easier to read (for example adding margin to both sides of the page so the content is in the middle and doesn't stretch to the whole screen.) For now, it's using the same default styles that we're using in chaise for the markdown column types.

**Comment by carlkesselman** [comment]
If the goal is to host directly in chaise, Is there any reason why we should not store this in hatred  or use the ability to store directly in the catalog?

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Oct 28, 2020, 5:43 PM -0700, Aref Shafaei <notifications@github.com>, wrote:

@carlkesselman<https://github.com/carlkesselman> The content is part of the chaise repository, under the same wiki folder. For example, this is the one page that we have right now:
https://github.com/informatics-isi-edu/chaise/blob/annotation-documentation/wiki/viewer-annotation.md

**Comment by hongsudt** [comment]
This is an embedded chaise help doc. Directly store it in the repo makes it simple to maintain and always available without dependence on external services. Other chaise documentations are stored in the repo under docs/ folder, same as other repos for maintaining documents (an agreement we established for documentations across software)The per deployment config files can be stored in hatrac or other places  and configured during make install.On Oct 28, 2020 18:24, Carl Kesselman <notifications@github.com> wrote:

If the goal is to host directly in chaise, Is there any reason why we should not store this in hatred  or use the ability to store directly in the catalog?







Carl







----------------------------------------------------------







Dr. Carl Kesselman



Dean’s Professor, Epstein Department of Industrial and Systems Engineering



Fellow, Information Sciences Institute Viterbi School of Engineering Professor,







Preventive Medicine Keck School of Medicine







University of Southern California



4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695



Phone:  +1 (310) 448-9338



 Email:  carl@isi.edu



Web: http://www.isi.edu/~carl



On Oct 28, 2020, 5:43 PM -0700, Aref Shafaei <notifications@github.com>, wrote:







@carlkesselman<https://github.com/carlkesselman> The content is part of the chaise repository, under the same wiki folder. For example, this is the one page that we have right now:



https://github.com/informatics-isi-edu/chaise/blob/annotation-documentation/wiki/viewer-annotation.md

**Comment by carlkesselman** [comment]
So then we are assuming that a per-deployment GitHub repo is a standard part of what we will have?

Please keep in mind that our goal is to have AWS hosted deployments, and many of them and we need to ensure that as much configuration and maintenance can be pushed out to non-ISRD people as possible.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine
Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl









On Oct 29, 2020, at 9:15 AM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


This is an embedded chaise help doc. Directly store it in the repo makes it simple to maintain and always available without dependence on external services. Other chaise documentations are stored in the repo under docs/ folder, same as other repos for maintaining documents (an agreement we established for documentations across software)The per deployment config files can be stored in hatrac or other places  and configured during make install.On Oct 28, 2020 18:24, Carl Kesselman <notifications@github.com<mailto:notifications@github.com>> wrote:
If the goal is to host directly in chaise, Is there any reason why we should not store this in hatred or use the ability to store directly in the catalog?



Carl



----------------------------------------------------------



Dr. Carl Kesselman

Dean’s Professor, Epstein Department of Industrial and Systems Engineering

Fellow, Information Sciences Institute Viterbi School of Engineering Professor,



Preventive Medicine Keck School of Medicine



University of Southern California

4676 Admiralty Way, Suite 1001, Marina del Rey, CA 90292-6695

Phone: +1 (310) 448-9338

Email: carl@isi.edu<mailto:carl@isi.edu>

Web: http://www.isi.edu/~carl

On Oct 28, 2020, 5:43 PM -0700, Aref Shafaei <notifications@github.com<mailto:notifications@github.com>>, wrote:



@carlkesselman<https://github.com/carlkesselman> The content is part of the chaise repository, under the same wiki folder. For example, this is the one page that we have right now:

https://github.com/informatics-isi-edu/chaise/blob/annotation-documentation/wiki/viewer-annotation.md

**Comment by karlcz** [comment]
I think there's some confusion here, maybe triggered by the word "wiki"?

As I understand it, this is just an internal function of chaise
software and deployed like all the other static assets in chaise (for
angular templates, icons, CSS, etc.)

It is NOT a project-specific asset nor a collaborative tool.  It is
maintained by the Chaise developers like any other tightly-integrated
bit of the HTML templates or the documentation that goes with a
version of the software.  It would be installed/updated automatically
in the same step that installs updated Chaise code on the web server.

The use of "wiki" was just an unfortunate way to refer to the syntax
of the source content that the Chaise developers will maintain by
hand...  a markdown dialect rather than angular and HTML template
code.  It is not about content management at all.

**Comment by RFSH** [comment]
Our goal for this PR was to be able to have some sort of help pages for complex parts of Chaise directly in the Chaise UI. So when users navigate to those pages, they don’t get lost without a way back to Chaise (so we decided against directing them to deriva docs, or Github).

We already have two of such pages as I mentioned in the PR. We just never thought about doing it in a reproducible way.  The wiki (which I realized is a bad term and I changed it to "help" instead) that I added is just like any other Chaise app/module that we have. All the content and template are part of the Chaise module and will be deployed with the same `make install` command alongside the rest of the Chaise. it’s just an easier way for us (Chaise developers) to just focus on writing documentation without worrying about the template each time.

I'm not trying to introduce a way to allow users of Chaise to modify the content of these documents.

**Comment by RFSH** [comment]
@jrchudy The PR is ready to be reviewed and merged. Please let me know if you have any concerns about this new app so we can discuss it.  As we discussed earlier, we're not going to change any of the existing help pages right now, and this is only used for viewer app drawing help.

**Review by jrchudy — APPROVED** [review]

**Pull request merged**
