### PR TITLE
Just a UI fix to recordedit for reducing top margin

### PR DESCRIPTION
**Pull request by chiragsanghvi**
This PR reduces the padding between the add and actual form in recordedit.

https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#19067/product:accommodation.

This is how it looked before

https://dev.isrd.isi.edu/chaise/recordedit/#19067/product:accommodation

Let me know if the url is not accessible. I cannot work on the default catalog as I don't have privileges to edit anything.

### CODE REVIEW

**Comment by hongsudt** [comment]
I am not sure I can see any difference on the provided url. Please assign
the person who raised the ux issue to review the ux.

**Comment by chiragsanghvi** [comment]
## Before 
screen shot 2017-03-08 at 2 36 08 pm



## After 
screen shot 2017-03-08 at 2 35 58 pm

**Comment by karlcz** [comment]
I see that the padding at the top is smaller w/ Firefox.  It is now approximately the height of the `[+|v]` button whereas the "before" link has about 2.5 or 3 of those heights.

**Comment by jrchudy** [comment]
You can easily see the difference with a side-by-side comparison. This looks good to me.

For a direct side-by-side comparision:
image

**Pull request merged**
