### PR TITLE
UX mitigation

### PR DESCRIPTION
**Pull request by RFSH**
[ermrestjs PR](https://github.com/informatics-isi-edu/ermrestjs/pull/809)

Fixed issues as part of this PR: #1843 #1851 #1680 #1836 #1835 #1849 #1507

### CODE REVIEW

**Comment by jrchudy** [comment]
### download buttons:
  - update download documentation for “btn btn-primary”
  - have a separate class for new download styling (default heuristic for generated content by ermrestJS)
    * allows for old deprecated styles to still be used
  - user-doc "style guide" that points out classes that users can apply in MD environment to add styling

### other changes:
 - TOOLTIPS !!! 
 - side bar button bug on record
 - verify spacing for record

**Comment by jrchudy** [comment]
- user-doc "style guide" that points out classes that users can apply in MD environment to add styling

 - toc
    * toc change name to "Sections"
    * move too title above to top-left panel
    * tooltips on right of them  (why tooltip?)
    * change "hide side panel" to "hide panel
  - facet panel
    * hide filter panel button should move left a little bit
    * change "hide filter panel" to "hide panel"
  - sed commands in makefile for version so it's a variable
  - chaise-icons are misaligned because of font size changes
  - *-sm classes for more responsive
  - i icon
    * headers should be smaller and superscript
    * move into : for record page
    * clean up uncurled edge in icon

After the above is done, send url link to ISRD to ask team what they think about the state of chaise with the mitigation changes.

  - apply mitigation styles to recordedit page
    * title update to be consistent with other pages
      ~ create/edit remains up top
      ~ row name is 2nd heading
    * clean up

**Comment by RFSH** [comment]
We have a discussion about these changes and the following are requested changes:

General
- [ ] tooltip placement
- [ ] Export button should be disabled instead of hidden when data is loading

Recordedit
- [ ] The markdown editor height is not set properly on load
- [ ] Boolean null should be "No Value"

Record page
- [ ] Maybe add border to the left of table of contents?
- [x] ~Show empty sections maybe needs to go to the right? Not now.~

Recordset
- [ ] Placeholder for search box should not go to next line.
- [ ] You shouldn’t be able to select show more when match-not-null and then it should have a tooltip why it’s disabled.
- [ ] Facet title spinner goes to next line when shrinked
- [ ] Remove the spinner from searchInput 
- [ ] Fix the responsiveness of main search box (use the space)
- [ ] Bullets in the markdown_container for the recordset are clipped (Gene)
- [ ] Document hide_num_occurrences and sort for facets

Table header (displaying..)
- [ ] Use digit grouping for total number of records (comma separator)
- [ ] the spacing of the cart should be the same as the care in export button (more space
- [ ] The dropdown -> checkbox should be right? (Maybe we should change the background color instead of having checkmark)
- [ ] Disable while the page is loading


Modals
- [ ] Remove the border bottom for the modal-header
- [ ] Change "X" button to "close"

Facet modal
- [ ] The spacing for the top-right-panel is wrong.
- [ ] Squeeze number of occurrences column.
- [ ] Scalar modal should use the smaller modal version
- [ ] Double spinner issue
- [ ] Remove match-null and match-not-null

Add pure and binary modal
- [ ] Submit should be disabled when there's nothing selected
- [ ] The disabled rows link colors should be the same grey as other rows
- [ ] For selected rows: decrease the spacing + remove the border (it should be diff. from filters)
- [ ] Clear all selected rows -> Reset selection
- [ ] Title of the modal should behave the same as recordset page title
- [ ] Reduce the spacing on top of the modal
- [ ] Title should be "Add TABLE to PARENT_TABLE: <small>ROWNAME</small>"
- [ ] Title should be just one line and we should show ellipsis with tooltip

Profile modal
- [ ] Should be the same as the record main content
- [ ] Change order: Displayname, full name, email, id, identities, groups

**Comment by RFSH** [comment]
Newly requested changes:

Record
- [ ] Decrease the padding of main entity table rows (should be the same as the old design which is 5px padding).
- [ ] The "Create" button in modal popups should be using the secondary styles.
- [ ] The logic for turning of the sticky area should be called sooner. The minimum height should be increased.
- [ ] The caret in dropdown for changing the page size is too small.
- [ ] The plus button in recordedit should be redesigned.

**Comment by RFSH** [comment]
Popup:
- [ ] The modal width should be based on the number of columns, later we might want to do annotation, or we might want to make the modal draggable.

Facet popup:
- [ ] Search box in the facet popup should be bigger (bigger min-width?)
- [ ] Modal sizes should be based on screen size?? Currently it’s based on vh and vw, but if you squeeze the whole page it will be small.
- [ ] The modal header must be sticky no matter what… the search and selected rows are not as important
- [ ]  Squeeze space between “X” and selected rows
- [ ]  the selected rows not using the 
- [ ] The spacing between “Reset selection” and the above is not correct.
- [ ] where should we put the x if the selected row is bigger than the line and wraps?
- [ ] selected rows shouldn’t be button group.
- [ ] The value of selected row should white space wrap.
- [ ] When you go from one mode of scroll to the other one, it’s not updating the styles somehow, it’s adding extra scrollbar.
- [ ] Go to protocol, search title for PCR-based -> and open modal -> fix the spacing of that one.

Recordset
- [ ] Change “Edit” button to “Bulk edit"

Recordedit:
- [ ] boolean
    - [ ] Adjust the width of dropdown to be the same as input
    - [ ] Close the dropdown to the input
- [ ] Align “Set value for all records:” vertically in the middle.
- [ ] Change the icon of the removing forms.
- [ ] The “X” icon for closing the “apply all” to be something else.
- [ ] “Add more forms:”
    - [ ] Use the same style as date and time to be like the following: (Qty.)[number](Clone), or “Clone: "
    - [ ] The tooltip should be more informative: duplicate rightmost form the specified number of times.
    - [ ] Add mask to it that you can only use 1-200
- [ ] The horizontal and vertical scrollbar should be in the same container.
- [ ] The upper horizontal scrollbar should be sticky.
- [ ] Decrease the space between lower and the sticky area
- [ ] The YYY-MM-DD and HH:mm:ss 
    - [ ] should use the correct color for placeholder
    - [ ] Should be all capital-case
- [ ] Markdown editor:
    - [ ] The "?" button should be grouped with the other two so we have 4 groups.
    - [ ] Decrease the spacing so we can have only two rows of buttons.

Foreignkey picker
- [ ] The Create button is misspelled
- [ ] Create: Tooltip: Create new “name"
- [ ] The vertical alignment is not properly set (the table is smaller).

Record page
- [ ] Bullets are not disabled for markdown.
- [ ] Move the buttons inside the span and align to the right…?

Navbar:
- [ ] The space between caret and text for the dropdowns that have another menu is not enough.

**Comment by jrchudy** [comment]
- [ ] autoscroll on next/previous click for recordset app
  - [ ] make sure this happens when new filters are selected too

- column headers in tables
  - [ ] sort icon overlaps info icon

- recordedit
  - [ ] white box to left of scroll bar for top sticky scrollbar
  - [ ] focus on add x forms input grays right border

**Pull request merged**
