### PR TITLE
Added a datepicker in sidebar

### PR DESCRIPTION
**Pull request by howdyjessie**

### CODE REVIEW

**Comment by robes** [comment]
This is great. There are a couple things you can fix.

1. There are some files that don't need to be added:
    - `.DS_Store`
    - `.project`

2. In various files in your source, some left over lines from your merge conflict that start with:
    - `<<<<<<<<<<<`
    - `===========`
    - `>>>>>>>>>>>`

**Comment by svoinea** [comment]
In ermrestSideBarController.js, it seems that some lines were removed:

-	$scope.FacetsData = FacetsData;
-	$scope.filtersStatus = {};
-	$scope.filtersMatch = {};
-	$scope.selectedCollection = '';

I'm not sure if that is OK.

**Comment by robes** [comment]
Any suggestions for testing the relevant code path?

**Comment by howdyjessie** [comment]
I'm pretty sure I messed up in ermrestSideBarController.js (re: Serban's comment) while fixing the conflicts. I don't have access to a computer right now to fix and test but I'll get on that asap.

**Comment by howdyjessie** [comment]
Hi, apologies for the delay. I realized it's easier if I made my edits back on my work machine.

I've removed the remaining merge conflicts (I should've looked more closely at the diff on Friday :-1: ), removed .DS_Store and .project, and re-inserted the code in ermrestSideBarController.js.

**Pull request closed without merging**
