### PR TITLE
Search popup

### PR DESCRIPTION
**Pull request by chiragsanghvi**
This PR implements the search feature as described in issue #791 

The search directive has 2 variables viz. backgroundSearch & foregroundSearch to track which search is going on currently.

Changes can be seen [here](https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#1/legacy:dataset)

The recordset app needs to change a bit, because it updates the whole page while you're typing text in search input box. I have added a switch to enable/disable the auto search.

The delay is 200ms for now.

### CODE REVIEW

**Comment by chiragsanghvi** [comment]
I updated the branch width changes as suggested by @hongsudt to have same behavior for search in recordset app too.

The recordset can checked [here](https://dev.isrd.isi.edu/~chirag/chaise/recordset/#1/legacy:dataset@sort(id)?limit=15)

**Comment by shinyichen** [comment]
Hongsuda wanted me to take a look at this PR even though it's already merged. Are the followings implemented?
1. If we have already started a foreground search, discard any background search result that arrives. ---- It seems every read result will update the table.
2. Ideally, lock the search input as busy while a foreground search is
pending. ---- although it says ideally, I wonder if you just missed it since it's a small change.

**Comment by chiragsanghvi** [comment]
1. I have added an explicit check to discard background search whenever a foreground search is going on. That kind of takes care of the situation.

2. Whenever you fire a foreground search, the search box is behind the spinner, and hence it gets disabled automatically. This is for the popup. I am not sure about the spinner in recordset. I can change it if the spinner doesn't covers the whole page.

**Comment by shinyichen** [comment]
This is the sequence I meant. 
1. background search started, search() function is called.
2. user clicks enter (bg flag is disabled, but task 1 is already reading)
3. task 1's read() comes back with result. (**The spec says this result should be discarded.)
4. Foreground search comes back with result.

**Pull request merged**
