### PR TITLE
Channel list hiding issue

### PR DESCRIPTION
**Pull request by vipul-21**
As mentioned by in the [PR comment](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/9#issuecomment-571813906), the channel list button was disabled even when the channel list were present. 
Note: Dependency on the  [openseadragon viewer PR](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/10).

### CODE REVIEW

**Comment by svoinea** [comment]
I have tested on `rbk-dev` with `chaise annotation-list` and `openseadragon multiple-annotations`.

I'd recommend a better stylesheet for displaying the channel list, as blue text on a grey background makes it difficult to be read. 

I'm attaching a screenshot on how it looks now:

Screenshot

**Comment by vipul-21** [comment]
The openseadragon viewer PR is merged.

**Comment by jrchudy** [comment]
As @svoinea mentioned, verify with hongsuda that this is the color contrast we want to use. The blue is a little bit too dark and doesn't contrast enough with the black background.

**Comment by vipul-21** [comment]
@hongsudt, The new color scheme for channel list is this. Please confirm if this is okay.  
screenshot

**Comment by vipul-21** [comment]
This PR is dependent with the openseadragon [PR](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/12).

**Comment by iamyle0710** [comment]
The changes look good to me on the viewer app part.

**Comment by vipul-21** [comment]
@svoinea Can you approve this well ?

**Pull request merged**
