### PR TITLE
Recordset prototype

### PR DESCRIPTION
**Pull request by robes**
For more information and examples, see https://github.com/informatics-isi-edu/chaise/issues/264

### CODE REVIEW

**Comment by shinyichen** [comment]
* sort by column
* paging
* permalink

**Comment by robes** [comment]
@shinyichen and @hongsudt : just wondering what the status is with this PR? is it going to be merged or do we need to discuss it?

**Comment by hongsudt** [comment]
Somehow this is closed due to the merge.. Can't figure out how to reopen the issue. Will create another issue.

**Comment by robes** [comment]
@hongsudt this was the pull request (not an issue), so it is now merged and closed.

**Pull request merged**
