### PR TITLE
record app: add function to convert markdown to html

### PR DESCRIPTION
**Pull request by RFSH**
This PR adds a function to record app that converts value of columns that are `markdown` typed into html.

### CODE REVIEW

**Comment by hongsudt** [comment]
How do I test this? which branch should I checkout to see the changes?

**Comment by RFSH** [comment]
I added my changes to record-markdown branch.

**Comment by hongsudt** [comment]
Can you tell me the url that will lead me to a table with a markdown
column..

**Comment by RFSH** [comment]
I didn't create any table with markdown. I just tested it on my own machine.

**Comment by hongsudt** [comment]
Please create a table with a markdown column. We will need this to work/test on record 2 anyway. @chiragsanghvi already has a test schema with a table with all supported column types. Can you work with him to extend his test table to include the markdown column?

**Comment by RFSH** [comment]
@hongsudt 

I created [this](https://dev.isrd.isi.edu/chaise/record/#1441/schema:markdown/id=123) sample data. The `description` column has `markdown` type and should be converted into html; while the `text` column is `markdown` typed.

Can you please checkout dev.isrd.isi.edu to `record-markdown` branch and test it?

**Comment by RFSH** [comment]
@hongsudt 

Take a look at [this](https://dev.isrd.isi.edu/~ashafaei/chaise/record/#1441/schema:markdown/id=123). Compare it to the link from previous comment.

**Pull request merged**
