### PR TITLE
Markdown table styling 

### PR DESCRIPTION
**Pull request by amitjha21**
This PR addresses markdown styling issue #1421.
Markdown preview and rendering is now based on GitHub markdown styles.

### CODE REVIEW

**Comment by RFSH** [comment]
I think having these css rules in an extra file is a better approach. It's true that we're using the github markdown css, but there might some styles that we don't like and we want to change. So I think it's better if we add these github css in a separate file (the same way that bootstrap css is separated from ours). Then if we want to change that, we can overwrite those rules in the app.css .

If your concern is performance, we should eventually add a step to Makefile to concatenate and minify all the css files into one.

**Comment by amitjha21** [comment]
Created a separate file for styling. `common/vendor/MarkdownEditor/styles/github-markdown.css` has all unminified styling css.

**Comment by RFSH** [comment]
Thanks. Since now we're treating it as a third-party library you can minify it. Just add the link to its source (the repository that you borrowed the code from), and also add a comment that the container class is `markdown-container` (the source had a different class for it). Also I think you missed recordedit in your resources. Our makefile is a bit messy, I think I should create an issue to clean it up.

**Comment by amitjha21** [comment]
The `recordedit` resource is there via MarkdownEditor entry in the `Makefile`.

**Pull request merged**
