### PR TITLE
More less changes

### PR DESCRIPTION
**Pull request by chiragsanghvi**
This PR fixes issues #819 and #820. 

https://synapse-dev.isrd.isi.edu/~chirag/chaise/recordset/#1/Zebrafish:Behavior@sort(Image%20Date::desc::)

### CODE REVIEW

**Comment by karlcz** [comment]
Does this include a change to the threshold for truncation?  I am trying to test the more-less branch but not seeing the behavior anymore...

**Comment by chiragsanghvi** [comment]
Yes. Hongsuda asked me to increase the default size to 160px.  I read it from chaise-config. So you just need to set the parameter `maxRecordsetRowHeight` in chaise-config to change it.

**Comment by karlcz** [comment]
This is not working right on synapse-dev....  when I set the max height to 150 and then see the "... more" link, clicking it makes the row shorter rather than taller and the "... less" control is missing.

**Comment by chiragsanghvi** [comment]
@karlcz Sorry about that. I was referring the wrong variable to check the overflow. Jenifer made some changes to the ellipsis plugin and I forgot to consider them in my branch. Have fixed it and updated the userdir website above

**Pull request merged**
